language: minimal
services:
  - docker

env:
  global:
  - DOCKER_REGISTRY=docker.pkg.github.com/llcoolsouder
  - IMAGE_NAME=$DOCKER_REGISTRY/developmentenvironment/dev-env:latest

before_install:
  - apt-get install -y pass

script:
  - docker build -t $IMAGE_NAME -f DevEnv.dockerfile .

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY
    - docker push $IMAGE_NAME
  on:
    branch: add-travis-config
